spring.application.name=gestion-tareas

# Configuracion de la base de datos H2 (en memoria para desarrollo)
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Consola H2 habilitada para acceder en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.settings.web-allow-others=true
